/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AutoComplete: typeof import('./components/shared/base/AutoComplete.vue')['default']
    BrandName: typeof import('./components/shared/icons/BrandName.vue')['default']
    CorrectCase: typeof import('./components/edit/toolbar/CorrectCase.vue')['default']
    DisplayInput: typeof import('./components/shared/base/DisplayInput.vue')['default']
    Dropdown: typeof import('./components/shared/base/Dropdown.vue')['default']
    Editor: typeof import('./components/edit/Editor.vue')['default']
    File: typeof import('./components/edit/toolbar/File.vue')['default']
    FileOptions: typeof import('./components/resumes/FileOptions.vue')['default']
    FontFamily: typeof import('./components/edit/toolbar/FontFamily.vue')['default']
    FontSize: typeof import('./components/edit/toolbar/FontSize.vue')['default']
    Header: typeof import('./components/shared/Header.vue')['default']
    ImportPane: typeof import('./components/edit/toolbar/ImportPane.vue')['default']
    LineHeight: typeof import('./components/edit/toolbar/LineHeight.vue')['default']
    Logo: typeof import('./components/shared/icons/Logo.vue')['default']
    Margins: typeof import('./components/edit/toolbar/Margins.vue')['default']
    NavItem: typeof import('./components/shared/base/NavItem.vue')['default']
    NewResume: typeof import('./components/resumes/NewResume.vue')['default']
    Paper: typeof import('./components/edit/toolbar/Paper.vue')['default']
    ParagraphSpace: typeof import('./components/edit/toolbar/ParagraphSpace.vue')['default']
    PopupPane: typeof import('./components/shared/base/PopupPane.vue')['default']
    Preview: typeof import('./components/edit/Preview.vue')['default']
    RenameResume: typeof import('./components/edit/header/RenameResume.vue')['default']
    ResumeInfo: typeof import('./components/resumes/ResumeInfo.vue')['default']
    ResumeItem: typeof import('./components/resumes/ResumeItem.vue')['default']
    ResumeOptions: typeof import('./components/resumes/ResumeOptions.vue')['default']
    ResumeRender: typeof import('./components/shared/ResumeRender.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveResume: typeof import('./components/edit/header/SaveResume.vue')['default']
    ThemeColor: typeof import('./components/edit/toolbar/ThemeColor.vue')['default']
    ToggleDark: typeof import('./components/shared/ToggleDark.vue')['default']
    ToggleLang: typeof import('./components/shared/ToggleLang.vue')['default']
    ToggleToolbar: typeof import('./components/edit/header/ToggleToolbar.vue')['default']
    Toolbar: typeof import('./components/edit/Toolbar.vue')['default']
    ToolItem: typeof import('./components/edit/toolbar/ToolItem.vue')['default']
  }
}
