// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/base/Button.vue')['default']
    Dropdown: typeof import('./components/base/Dropdown.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    File: typeof import('./components/file/File.vue')['default']
    FontCN: typeof import('./components/tools/FontCN.vue')['default']
    FontEN: typeof import('./components/tools/FontEN.vue')['default']
    FontSize: typeof import('./components/tools/FontSize.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Import: typeof import('./components/file/Import.vue')['default']
    LineHeight: typeof import('./components/tools/LineHeight.vue')['default']
    MarginHorizontal: typeof import('./components/tools/MarginHorizontal.vue')['default']
    MarginVertical: typeof import('./components/tools/MarginVertical.vue')['default']
    OhCV: typeof import('./components/icons/OhCV.vue')['default']
    Paper: typeof import('./components/tools/Paper.vue')['default']
    ParagraphSpace: typeof import('./components/tools/ParagraphSpace.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeColor: typeof import('./components/tools/ThemeColor.vue')['default']
    ToggleDark: typeof import('./components/ToggleDark.vue')['default']
    ToggleLang: typeof import('./components/ToggleLang.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
  }
}

export {}
