// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AutoComplete: typeof import('./components/base/AutoComplete.vue')['default']
    CorrectCase: typeof import('./components/toolbar/CorrectCase.vue')['default']
    Dropdown: typeof import('./components/base/Dropdown.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    File: typeof import('./components/toolbar/File.vue')['default']
    FontFamily: typeof import('./components/toolbar/FontFamily.vue')['default']
    FontSize: typeof import('./components/toolbar/FontSize.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ImportPane: typeof import('./components/toolbar/ImportPane.vue')['default']
    LineHeight: typeof import('./components/toolbar/LineHeight.vue')['default']
    Logo: typeof import('./components/icons/Logo.vue')['default']
    Margins: typeof import('./components/toolbar/Margins.vue')['default']
    NavItem: typeof import('./components/base/NavItem.vue')['default']
    Pane: typeof import('./components/base/Pane.vue')['default']
    Paper: typeof import('./components/toolbar/Paper.vue')['default']
    ParagraphSpace: typeof import('./components/toolbar/ParagraphSpace.vue')['default']
    PopupPane: typeof import('./components/base/PopupPane.vue')['default']
    RenameResume: typeof import('./components/header/RenameResume.vue')['default']
    ResumeOptions: typeof import('./components/header/ResumeOptions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchResume: typeof import('./components/header/SwitchResume.vue')['default']
    ThemeColor: typeof import('./components/toolbar/ThemeColor.vue')['default']
    ToggleDark: typeof import('./components/header/ToggleDark.vue')['default']
    ToggleLang: typeof import('./components/header/ToggleLang.vue')['default']
    ToggleToolbar: typeof import('./components/header/ToggleToolbar.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
    ToolItem: typeof import('./components/toolbar/ToolItem.vue')['default']
    Zoom: typeof import('./components/Zoom.vue')['default']
    ZoomCom: typeof import('./components/ZoomCom.vue')['default']
  }
}
